CREATE TABLE IF NOT EXISTS USERS (
  id_user SERIAL PRIMARY KEY,
  pseudo VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  mdp VARCHAR(255) NOT NULL,
  user_role VARCHAR(255) NOT NULL,
  UNIQUE(pseudo, mdp)
  );

CREATE TABLE IF NOT EXISTS FILM (
  id_film SERIAL PRIMARY KEY,
  titre VARCHAR(255) NOT NULL,
  realisateur VARCHAR(255) NOT NULL,
  annee INT,
  genre VARCHAR(255) NOT NULL,
  UNIQUE(titre, realisateur)
  );

CREATE TABLE IF NOT EXISTS ACTOR (
  id_actor SERIAL PRIMARY KEY,
  nom VARCHAR(255) NOT NULL,
  prenom VARCHAR(255) NOT NULL,
  UNIQUE(nom, prenom)
  );

CREATE TABLE IF NOT EXISTS FAVORIS (
  id_user INT NOT NULL,
  id_film INT NOT NULL,
  PRIMARY KEY (id_user, id_film),
  FOREIGN KEY (id_user) REFERENCES USERS(id_user) ON DELETE CASCADE,
  FOREIGN KEY (id_film) REFERENCES FILM(id_film) ON DELETE CASCADE
  );

CREATE TABLE IF NOT EXISTS CASTING (
  id_film INT NOT NULL,
  id_actor INT NOT NULL,
  PRIMARY KEY (id_film, id_actor),
  FOREIGN KEY (id_film) REFERENCES FILM(id_film) ON DELETE CASCADE,
  FOREIGN KEY (id_actor) REFERENCES ACTOR(id_actor) ON DELETE CASCADE
  );
