apiVersion: v1
kind: Secret
metadata:
  name: secrets-application
type: Opaque
data:
  # Les valeurs doivent être encodées en base64.
  # Commande pour encoder :
  # echo -n "ma-cle-secrete" | base64
  TMDB_API_KEY : N2U3YmI5ODI5MmI0NGVlZDgwYzdhZmMyM2Q5NTMxMGU=
  TMDB_API_TOKEN : RXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKaGRXUWlPaUkzWlRkaVlqazRNamt5WWpRMFpXVmtPREJqTjJGbVl6SXpaRGsxTXpFd1pTSXNJbTVpWmlJNk1UYzNNREEwTkRrek1pNDNNVGd3TURBeUxDSnpkV0lpT2lJMk9UZ3dZbVV3TkRKbE1tUXpOMkk0WkdSaU1qRXpZVGtpTENKelkyOXdaWE1pT2xzaVlYQnBYM0psWVdRaVhTd2lkbVZ5YzJsdmJpSTZNWDAuZHNLWnc1S2F2bm1zTlpmY1NOVTR3dmFydXgzT1VSaDhRQU5aa2RwNTRBQQ==
  API_KEY: bWEtY2xlLXNlY3JldGU=
  DATABASE_PASSWORD: cGFzc3dvcmQxMjM=
